config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  get 'notifications/index'

  get 'search/create'
  get "posts/modal" => 'posts#modal', :as => :modal
  get "posts/modalShare" => 'posts#modalShare', :as => :modalShare
  get "posts/PhotoPostModal" => 'posts#PhotoPostModal', :as => :PhotoPostModal
  get "friendships/modalFriends" => 'friendships#modalFriends', :as => :modalFriends
  get "comments/moreComments" => 'comments#moreComments', :as => :modalComments
  
  resources :notifications, only: [:index,:update]
  
  resources :posts do
    resources :comments
    resources :likes
    resources :dislikes
    resources :shares
    member do
        post :repost
        post :modal
    end
    
  end

  resources :areas do
    resources :votes
  end


  resources :likes
  devise_for :users
  resources :usuarios, as: :users,only: [:show,:update]
  get '/changeArea' , to: 'main#changeArea'
  
  
  resources :friendships, only: [:create,:update,:index]
  resources :votes, only: [:create,:update,:index]
  
  
  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Notificable
  belongs_to :post
  belongs_to :user

  def user_ids
  	self.post.NotificacionPost
    
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comments.new
  end

  def index
    @postts = Post.find(params[:post_id])
    @Comments = @postts.comments

  end

  def show
    
  end

  def moreComments
    @postt = Post.find(params[:cualPost])
    if @postt.repost_id != nil
       @comentarios = Post.find(@postt.repost_id).comments.paginate(page:params[:page], per_page:3)
    else
       @comentarios = @postt.comments.paginate(page:params[:page], per_page:3)
    end
   

   respond_to do |format|
    format.html { redirect_to root_path }
    format.js {render :action => "moreComments" }
   end
    
  end


  def destroy
    @comment.destroy
    
  end

  def create

    @postt = Post.find(params[:post_id])

    if @postt.repost_id != nil
      @sharePost = Post.find(@postt.repost_id)
      @comment = @sharePost.comments.new(comment_params)
      @comment.commenter = current_user.username
      @comment.user_id = current_user.id
    else
      @comment = @postt.comments.new(comment_params)
      @comment.commenter = current_user.username
      @comment.user_id = current_user.id
    end


    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Acabas de comentar.' }
        format.js { render :show }
        #format.json { render :show, status: :created, location: @post }
  
      end
    end
    

  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter,:user_id ,:body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.haml
%article.large-paddingComment
      = link_to comment.commenter + ": " , comment.user, class:"indianRed-text NoUnderline lighter"
      = comment.body 

app/views/comments/_show.haml
%article.large-padding.white.top-space
  /Z
  
  %button.botonPost.mdl-button.mdl-js-button.mdl-button--icon.mdl-button--colored
    .material-icons
      thumb_up

  .text-left.relative
    =circle_img post.user.avatar.url(:medium),50
    .quitarMargenArriba.MargenIzquierdo
      =post.user.username

  
  %p.top-space.text-left.agregarMargenArriba=post.body


  %button.botonPost.mdl-button.mdl-js-button.mdl-button--icon.mdl-button--colored
    .material-icons
      thumb_down


  .text-right=post.area

  .text-right=post.megusta


%h2 Add a comment

=form_for ([@post, @post.comments.build]) do |f|
  %p
    = f.label :commenter
    = f.text_field :commenter
 
  %p
    = f.label :body
    = f.text_area :body
  
  %p
    = f.submit
  

app/views/comments/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Body
      %th User
      %th
      %th
      %th

  %tbody
    - @Comments.each do |comment|
      %tr
        %td= comment.body
        %td= comment.commenter
        %td= link_to 'Destroy', root_path, :method => :delete, :data => { :confirm => 'Are you sure?' } 

%br

/= link_to 'New Post', new_comment_path