config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  get 'notifications/index'

  get 'search/create'
  get "posts/modal" => 'posts#modal', :as => :modal
  get "posts/modalShare" => 'posts#modalShare', :as => :modalShare
  get "posts/PhotoPostModal" => 'posts#PhotoPostModal', :as => :PhotoPostModal
  get "friendships/modalFriends" => 'friendships#modalFriends', :as => :modalFriends
  get "comments/moreComments" => 'comments#moreComments', :as => :modalComments
  
  resources :notifications, only: [:index,:update]
  
  resources :posts do
    resources :comments
    resources :likes
    resources :dislikes
    resources :shares
    member do
        post :repost
        post :modal
    end
    
  end

  resources :areas do
    resources :votes
  end


  resources :likes
  devise_for :users
  resources :usuarios, as: :users,only: [:show,:update]
  get '/changeArea' , to: 'main#changeArea'
  
  
  resources :friendships, only: [:create,:update,:index]
  resources :votes, only: [:create,:update,:index]
  
  
  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_buscador.html.erb
<div class="buscador">
      <%=form_tag "/search/create", method: :get, remote: true, id:"search-form" do  %>
          <%=text_field_tag :keyword, nil, placeholder: "Search people", class:"labelBuscador" %>

          <button class="buttonBuscador" type="submit">Search</button>

     <!--     <%=content_tag :button,class:"botonBuscar" ,type: :submit do%>
            Search
          <% end %> -->


        <% end %>

      </div>

app/views/partials/_comentariosform.haml
=form_for [@post, @post.comments.build], remote: true do |f| # CREAR COMENTARIOS
   
  .mdl-textfield.mdl-js-textfield.full-width
    = f.text_field :body,class:"mdl-textfield__input",type:"text"  ,id: "sample1"
    = f.label :body, "Comment...",class:"mdl-textfield__label",for: "sample1"
    .ocultar.actions.text-right
      = f.submit 'Enviar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent"

app/views/partials/_dialogs.html.erb
 <dialog class="ajax-text-and-image white-popup-block" data-backdrop="true" id="popPost">
  	
  </dialog>


  <dialog id="popLikes" class="mdl-dialog" data-backdrop="true">

  	<div id="dialogo-Megusta">
  		
  	</div>
    
    <div class="mdl-dialog__actions">
      <button type="button" class="mdl-button" id="cerrar">Agree</button>

    </div>
  </dialog>

app/views/partials/_nav.html.erb
<header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title talk"><%=link_to "Talk", root_path,class:"NoUnderline white-text"%></span>

      <%= render "partials/buscador" %>

      <div class="mdl-layout-spacer"></div>
      <span class="mdl-layout-title area"><%=link_to $global_area_name, root_path,class:"NoUnderline white-text"%></span>

      <div class="right-space iconoNotificaciones">

          <%= link_to "/notifications" , class:"white-text iconoNotificaciones",remote: true,data: {type: "script"} do%> 
            <div id="notification" class="material-icons mdl-badge mdl-badge--overlap" data-badge="<%=current_user.unviewed_notifications_count%>">notifications</div>

          <% end %> 

      </div>


      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">

        <div id="searches"></div>
        <div id="notifications"></div>

        <%= link_to "library_books" , areas_path, class:"white-text material-icons md-36 NoUnderline hover"%> 

        <%= link_to "group" , friendships_path, class:"white-text material-icons md-36 NoUnderline hover"%> 
        <%= link_to "assignment_ind" , current_user, class:"white-text material-icons md-36 NoUnderline hover"%> 
        
        <%= link_to "exit_to_app" , destroy_user_session_path, method: :delete ,class:"white-text material-icons md-36 NoUnderline hover"%> 

        <div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" type="text" name="sample"
                 id="fixed-header-drawer-exp">
        </div>
      </div>
    </div>

    
  </header>


    <div class="mdl-layout__drawer ">
    <span class="mdl-layout-title">Talk</span>
    <nav class="mdl-navigation">

      <%= link_to "#Love", {controller:"main", action:"changeArea", my_param: 23, name:"#Love"}, class:"mdl-navigation__link nav_words" %>

      <%= link_to "#Talk", {controller:"main", action:"changeArea", my_param:"all" ,name:"#Talk"}, class:"mdl-navigation__link nav_words" %>

      <%= link_to "#Friends", {controller:"main", action:"changeArea", my_param: 1,name:"#Friends"}, class:"mdl-navigation__link nav_words" %>

      <%= link_to "#Love", {controller:"main", action:"changeArea", my_param: 2,name:"#Love"}, class:"mdl-navigation__link nav_words" %>

      <%= link_to "#School", {controller:"main", action:"changeArea", my_param: 3,name:"#School"}, class:"mdl-navigation__link nav_words" %>

      <div class="ocultar"> <%= @areasNav = Area.all.GoalTrue %> </div>
      
      <% @areasNav.each do |area| %>

      <%= link_to "#" +area.title, {controller:"main", action:"changeArea", my_param: area.id ,name: "#" + area.title}, class:"mdl-navigation__link nav_words" %>

    
      <% end %>

    </nav>
  </div>


  
  