config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  get 'notifications/index'

  get 'search/create'
  get "posts/modal" => 'posts#modal', :as => :modal
  get "posts/modalShare" => 'posts#modalShare', :as => :modalShare
  get "posts/PhotoPostModal" => 'posts#PhotoPostModal', :as => :PhotoPostModal
  get "friendships/modalFriends" => 'friendships#modalFriends', :as => :modalFriends
  get "comments/moreComments" => 'comments#moreComments', :as => :modalComments
  
  resources :notifications, only: [:index,:update]
  
  resources :posts do
    resources :comments
    resources :likes
    resources :dislikes
    resources :shares
    member do
        post :repost
        post :modal
    end
    
  end

  resources :areas do
    resources :votes
  end


  resources :likes
  devise_for :users
  resources :usuarios, as: :users,only: [:show,:update]
  get '/changeArea' , to: 'main#changeArea'
  
  
  resources :friendships, only: [:create,:update,:index]
  resources :votes, only: [:create,:update,:index]
  
  
  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true
  after_create {NotificationBroadcastJob.perform_later(self)}
  scope :unviewed, -> {where(viewed:false)}
  scope :latest, -> {order("created_at desc").limit(10)}

  def self.for_user(user_id)
  	Notification.where(user_id: user_id).unviewed.count

  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  	@notifications = Notification.where(user:current_user).unviewed.latest
  	respond_to do |format|
  		format.html
  		format.js
  	end
  end

  def update
  	@notification = Notification.find(params[:id])
  	message = if @notification.update(notification_params)
  		"Notificacion Vista"
  	else
  		"Hubo un error"
  	end
  	redirect_to :back, notice: message
  	
  end

  private
  def notification_params
  	params.require(:notification).permit(:viewed)
  		
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def render_notifications (notifications)
		notifications.map do |notification|
			render partial: "notifications/#{notification.item_type.downcase}", locals:{notification: notification}
		end.join("").html_safe
		
	end
end

app/views/notifications/_comment.haml
=link_to(PhotoPostModal_path(idpost_param: notification.item.post.id),:remote=>true,class:"linkNotificacion",for:".notificationQUITAR_#{notification.id}") do
	.text-left
		=circle_img notification.item.user.avatar.url(:medium),20
		=notification.item.user.username
		comento tu publicacion
		=link_to notification_path(id: notification.id,notification:{viewed: true}),class:"notification_#{notification.id} ocultar",method: :put do
			&#9989; 

app/views/notifications/_friendship.haml
%p
	Tu amigo
	=notification.item.user.username
	te agrego como amigo
	=link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put do
		&#9989; 

app/views/notifications/_like.haml
=link_to(PhotoPostModal_path(idpost_param: notification.item.post.id),:remote=>true,class:"linkNotificacion",for:".notificationQUITAR_#{notification.id}") do
	.text-left
		=circle_img notification.item.user.avatar.url(:medium),20
		=notification.item.user.username
		le dio me gusta a tu publicacion
		=link_to notification_path(id: notification.id,notification:{viewed: true}),class:"notification_#{notification.id} ocultar",method: :put do
			&#9989; 

app/views/notifications/_post.haml
%p
	Tu amigo
	=notification.item.user.username
	creo una nueva publicación
	=link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put do
		&#9989;

app/views/notifications/_share.haml
=link_to(PhotoPostModal_path(idpost_param: notification.item.post.id),:remote=>true,class:"linkNotificacion",for:".notificationQUITAR_#{notification.id}") do
	.text-left
		=circle_img notification.item.user.avatar.url(:medium),20
		=notification.item.user.username
		compartio tu publicacion
		=link_to notification_path(id: notification.id,notification:{viewed: true}),class:"notification_#{notification.id} ocultar",method: :put do
			&#9989; 

app/views/notifications/_vote.haml
%p
	Se ha creado el area que votaste
	=link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put do
		&#9989; 

app/views/notifications/index.html.haml
%h1 Notificaciones

=render_notifications @notifications