config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  get 'notifications/index'

  get 'search/create'
  get "posts/modal" => 'posts#modal', :as => :modal
  get "posts/modalShare" => 'posts#modalShare', :as => :modalShare
  get "posts/PhotoPostModal" => 'posts#PhotoPostModal', :as => :PhotoPostModal
  get "friendships/modalFriends" => 'friendships#modalFriends', :as => :modalFriends
  get "comments/moreComments" => 'comments#moreComments', :as => :modalComments
  
  resources :notifications, only: [:index,:update]
  
  resources :posts do
    resources :comments
    resources :likes
    resources :dislikes
    resources :shares
    member do
        post :repost
        post :modal
    end
    
  end

  resources :areas do
    resources :votes
  end


  resources :likes
  devise_for :users
  resources :usuarios, as: :users,only: [:show,:update]
  get '/changeArea' , to: 'main#changeArea'
  
  
  resources :friendships, only: [:create,:update,:index]
  resources :votes, only: [:create,:update,:index]
  
  
  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  area       :decimal(, )
#  usuario    :string
#

#Scaffold crea un CRUD  => Create, Read, Update, Delete
class Post < ApplicationRecord

  belongs_to :user
  scope :nuevos, ->{order("created_at desc")}
  #after_create :send_to_action_cable
  has_many :comments
  has_many :likes
  has_many :dislikes
  has_many :shares


  has_attached_file :photo
  validates_attachment_content_type :photo,
    :content_type => ['video/mp4'],
    :message => "Sorry, right now we only support MP4 video",
    :if => :is_type_of_video?
  validates_attachment_content_type :photo,
     :content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
     :message => "Different error message",
     :if => :is_type_of_image?
  
 #has_attached_file :photo,styles: {thumb:"100x100",medium:"300x300",popup:"500x500"}
 #validates_attachment_content_type :photo,content_type: /\Aimage\/.*\Z/

  #validates_attachment_content_type :photo,:content_type => ['video/mp4'],:message => "Sorry, right now we only support MP4 video"
  def already_shares?(user) 
    self.shares.where(user:user).any?
  end

  def already_likes?(user) 
    self.likes.where(user:user).any?
  end

  def already_dislikes?(user) 
    self.dislikes.where(user:user).any?
  end

  def already_shares?(user) 
    self.shares.where(user:user).any?
  end

  def self.all_for_user(user)
  Post.where(user_id: user.id)
    .or(Post.where(user_id: user.friend_ids))
    .or(Post.where(user_id: user.user_ids))

  end

  
  def self.all_for_area(var)
  Post.where(area: var)

  end

  def user_ids
    self.user.friend_ids + self.user.user_ids
    
  end

  def NotificacionPost
      return Post.find(self).user_id
 
  end


  private
    def send_to_action_cable
      
      data = {message:to_html, action:"new_post"}

      #yo agrege
      self.user.friend_ids.each do |friend_id|
        printf "AMIGOSSSSSSSSSSSS"
        ActionCable.server.broadcast "posts_#{friend_id}", data
      end

      # a mi me agregaron
      self.user.user_ids.each do |friend_id|
        ActionCable.server.broadcast "posts_#{friend_id}", data
      end
      
    end

    def to_html
      printf "ENTRO"
      ApplicationController.renderer.render(partial:"posts/post",locals: {post:self.decorate})
    
    end




  protected
  def is_type_of_video?
    photo.content_type =~ %r(video)
  end

  def is_type_of_image?
    photo.content_type =~ %r(image)
  end




end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.decorate

  # GET /posts/1
  # GET /posts/1.json
  end
  
  def show
    
  end

  # GET /posts/new
  def new
    @post = Post.new.decorate
  end

  # GET /posts/1/edit
  def edit
  end

  def PhotoPostModal
    @post=Post.find(params[:idpost_param]).decorate

    if @post.photo_file_name != nil
      respond_to do |format|
      format.html
      format.js { render :action => "modalPicture" }
      end
    else
      respond_to do |format|
      format.html
      format.js { render :action => "modalWithOutPhoto" }
      end

    end
    
  end

  def modal
    @post=Post.find(params[:idpost_param])
    respond_to do |format|
    format.html
    format.js { render :action => "modaljs" }
    end
    
  end

  def modalShare
    @post=Post.find(params[:idpost_param])
    respond_to do |format|
    format.html
    format.js { render :action => "modalSharesjs" }
    end
    
  end

  def repost
    orig_post=Post.find(params[:id])
    if  orig_post.already_shares?(current_user) == false

      if(orig_post.repost_id!=nil) #saber si ya se habia compartido
        puts "post compartido"
        @post= Post.create(user_id:current_user.id, 
          body: orig_post.body,
          area: orig_post.area, 
          photo: orig_post.photo, 
          repost_id:orig_post.repost_id).decorate
        respond_to do |format|
          format.html { redirect_to root_path, notice: 'Post was successfully created.' }
          format.js { render :action => "sharejs" }
          format.json { render :show, status: :created, location: @post }
        
        end
      else
        if(orig_post) #primera vez que se comparte
          @post= Post.create(user_id:current_user.id, 
            body: orig_post.body,
            area: orig_post.area, 
            photo: orig_post.photo, 
            repost_id:orig_post.id).decorate
          respond_to do |format|
            format.html { redirect_to root_path, notice: 'Post was successfully created.' }
            format.js { render :action => "sharejs" }
            format.json { render :show, status: :created, location: @post }
        
          end
        
        end 

      end

    end
    
  end


  # POST /posts
  # POST /posts.json
  def create
    
    @post = current_user.posts.new(post_params).decorate
    @post.usuario = current_user.username #es lo de usuario, ya NO hace nade, si funciona, pero lo deje para saber
    @post.area = $global_area

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js { render :show }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :user_id,:area,:usuario, :photo )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post, remote: true do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .mdl-textfield.mdl-js-textfield.full-width
    = f.text_area :body,class:"mdl-textfield__input anchoLetra",row:"3"
    = f.label :body, "Talk...",class:"mdl-textfield__label"
    =f.file_field :photo,class:"ocultar updatePhoto",id:"uploadPhotoVideo"
  

  .actions.text-right
    %i.material-icons.md-30.upload-something.botonUpload{for:"#uploadPhotoVideo"} insert_photo
    %i.material-icons.md-30.upload-something.botonUpload{for:"#uploadPhotoVideo"} videocam
    %img#imgSalida.fotoForm{width:"60px", height:"50px", src:"" }

    = f.submit 'Share', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent"
    


          
              

app/views/posts/_modal.haml
%h4.text-center.tituloLikes
  =@post.likes.count
  Likes
%table
  %thead
    %tr
      %th
      %th
      %th
      %th

  %tbody
    - @post.likes.each do |like|
      .text-left.paddingLikes
        =circle_img like.user.avatar.url(:medium),50
        .quitarMargenArriba.MargenIzquierdo
          = like.user.username
          .line-block.text-right
            = link_to "Ver." ,like.user, class:"mdl-button mdl-js-button mdl-button--primary"

        

%br

app/views/posts/_modalPostPhoto.haml
.ajcol
  =image_tag(@post.photo, :alt => "error")
.ajcol2
  %article.large-padding.white.top-space

    .text-left.relative.padding-bottomPop
      =@post.iconoPost
      .quitarMargenArriba.MargenIzquierdo
        =@post.NombreUsarioPost
        .line-block.text-right
          =@post.fechaPost

    %p.top-space.text-left.letraPost.indianRed-text=@post.body

    %div.top-space
      /BOTON ME GUSTA
      =@post.buttonMeGusta
      /BOTON NO ME GUSTA
      =@post.buttonNOOMeGusta
      /BOTON SHARE
      =@post.CuantosShare
      =@post.ButtonShare

    %div.top-space2.indianRed-text.comentariosDialogPhoto{:id => "comentarios_#{@post.id}"}
      -if @post.repost_id != nil
        = render Post.find(@post.repost_id).comments
      -else 
        = render @post.comments





    =form_for [@post, @post.comments.build],id:"onclickNumber-share_#{@post.id}", remote: true do |f| 
     
      .mdl-textfield.mdl-js-textfield.full-width
        = f.text_field :body,class:"mdl-textfield__input",type:"text"  ,id: "sample2"
        = f.label :body, "Comment...",class:"mdl-textfield__label",for: "sample2"
        .ocultar.actions
          = f.submit 'Enviar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent"

    %button.ocultar.mdl-button#cerrarPopPhoto
      Agree



    

app/views/posts/_modalShares.haml
%h4.text-center.tituloLikes
  =@post.shares.count
  Shares
%table
  %thead
    %tr
      %th
      %th
      %th
      %th

  %tbody
    - @post.shares.each do |share|
      .text-left.paddingLikes
        =circle_img share.user.avatar.url(:medium),50
        .quitarMargenArriba.MargenIzquierdo
          = share.user.username
          .line-block.text-right
            = link_to "Ver." ,share.user, class:"mdl-button mdl-js-button mdl-button--primary"

        

%br

app/views/posts/_modalWithOutPhoto.haml
.ajcol3
  %article.large-padding.white.top-space

    .text-left.relative.padding-bottomPop
      =@post.iconoPost
      .quitarMargenArriba.MargenIzquierdo
        =@post.NombreUsarioPost
        .line-block.text-right
          =@post.fechaPost

    %p.top-space.text-left.letraPost=@post.body

    %div.top-space
      /BOTON ME GUSTA
      =@post.buttonMeGusta
      /BOTON NO ME GUSTA
      =@post.buttonNOOMeGusta
      /BOTON SHARE
      =@post.CuantosShare
      =@post.ButtonShare

    %div.top-space2.comentariosDialog{:id => "comentarios_#{@post.id}"}
      -if @post.repost_id != nil
        = render Post.find(@post.repost_id).comments
      -else 
        = render @post.comments




    =form_for [@post, @post.comments.build],id:"onclickNumber-share_#{@post.id}", remote: true do |f| 
     
      .mdl-textfield.mdl-js-textfield.full-width
        = f.text_field :body,class:"mdl-textfield__input",type:"text"  ,id: "sample2"
        = f.label :body, "Comment...",class:"mdl-textfield__label",for: "sample2"
        .ocultar.actions
          = f.submit 'Enviar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent"

    %button.ocultar.mdl-button#cerrarPopPhoto
      Agree



    

app/views/posts/_post.haml
%article.large-padding.white.top-space.mdl-shadow--2dp
  /.line-block.text-right=post.area
  
  -if post.repost_id != nil #COMPARTIÓ PUBLICACIÓN NUEVO!!
    %div.compartir
      .text-left.relative
        = post.linkPostUsuario
        Share this:



  .text-left.relative
    =post.iconoPost
    .quitarMargenArriba.MargenIzquierdo
      =post.NombreUsarioPost
      .line-block.text-right
        =post.fechaPost
         

  
  %p.top-space.text-left.agregarMargenArriba.letraPost=post.body  #TEXTO PUBLICACION
  
  
  /IMAGEN O VIDEO DE POST
  -if post.photo_file_name != nil
    -if post.photo.content_type =~ %r(image)    
      =link_to(PhotoPostModal_path(idpost_param: post.id),:remote=>true) do
        %div.padding-Picture.cover{:style=>"background-image: url(#{post.photo})"} 
    -else
      = video_tag post.photo, :size => "540x300", :controls => true
    

  %div.top-space
    /BOTON ME GUSTA
    =post.buttonMeGusta
    /BOTON NO ME GUSTA
    =post.buttonNOOMeGusta
    /BOTON SHARE
    =post.CuantosShare
    =post.ButtonShare

  /comentarios
  .ocultar
    -if post.repost_id != nil
      = @comentarios = Post.find(post.repost_id).comments.paginate(page:params[:comments_page], per_page:3)
    -else
      = @comentarios = post.comments.paginate(page:params[:comments_page], per_page:3) 
  
  %div{:id => "comentarios_#{post.id}"}
    = render @comentarios

    .ocultar{:id => "PaginateComentarios_#{post.id}"}
      = will_paginate @comentarios,:remote =>true,:class => "PaginateClasscomentarios_#{post.id}",:page => params[:comments_page], :params => { :controller => "comments", :action => "moreComments",cualPost: post.id}



  - if @comentarios.next_page 
    %a.pointer.moreComments.indianRed-text.lighter{:id => "#{post.id}"}
      see other
      = (@comentarios.count - 3)
      comments




  /Crear Comentarios !!!
  =form_for [post, post.comments.build],id:"onclickNumber-share_#{post.id}", remote: true do |f| 
   
    .mdl-textfield.mdl-js-textfield.full-width.quitarMargenAbajoComentario
      = f.text_field :body,class:"mdl-textfield__input",type:"text"  ,id: "sample1"
      = f.label :body, "Comment...",class:"mdl-textfield__label",for: "sample1"
      .ocultar.actions.text-right
        = f.submit 'Enviar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent"





  %div.ocultar
    =form_for [post, post.shares.build], remote: true do |f|
      = f.submit 'Enviar',id:"onclickNumber-share_#{post.id}" #BOTON SHARE PARA BD OCULTO


  %div.ocultar
    =form_for [post, post.dislikes.build], remote: true do |f|
      = f.submit 'favorite', id:"onclick-NOmegusta_#{post.id}" #BOTON NO ME GUSTA OCULTO
  %div.ocultar  
    =form_for [post, post.likes.build], remote: true do |f|
      = f.submit 'favorite', id:"onclick-megusta_#{post.id}" #BOTON ME GUSTA OCULTO


  %div.ocultar 
    =link_to "compartir", repost_post_path(post.id),id:"onclick-share_#{post.id}" ,method: :post,remote: true #BOTON SHARE PARA CREAR POST COMPARTIDO OCULTO 
  



      



  
  

  

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Body
      %th User
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.body
        %td= post.user
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/originalPost.haml
%article.large-padding.white.top-space
  /.line-block.text-right=post.area

  .text-left.relative   
    =circle_img post.user.avatar.url(:medium),50  #FOTO DE USUARIO
    .quitarMargenArriba.MargenIzquierdo
      = link_to post.user.username , post.user, class:"indianRed-text NoUnderline lighter"
      .line-block.text-right=post.created_at.strftime("%d %b. %Y")
         

  
  %p.top-space.text-left.agregarMargenArriba.letraPost=post.body  #TEXTO PUBLICACION

  
  /IMAGEN O VIDEO DE POST
  -if post.photo_file_name != nil
    -if post.photo.content_type =~ %r(image)    
      %a.with-caption.image-link{:href=>"#{post.photo}"}
        %div.padding-Picture.cover{:style=>"background-image: url(#{post.photo})"} 
    -else
      = video_tag post.photo, :size => "540x300", :controls => true
    

  %div.top-space
    /BOTON ME GUSTA
    -if post.already_likes?(current_user) == false
      =link_to "#{post.likes.count}",likes_path(id_del_post: post.id),id:"likes_#{post.id}",class:"NoUnderline indianRed-text lighter"
      =botonesPostMegusta post.id
    -else #YA ME GUSTA
      =link_to "#{post.likes.count}",likes_path(id_del_post: post.id),id:"likes_#{post.id}",class:"NoUnderline indianRed-text lighter"
      =botonesPostYaMegusta post.id
    /BOTON NO ME GUSTA
    -if post.already_dislikes?(current_user) == false
      =cuantosMegusta "dislikes_#{post.id}", post.dislikes.count
      =botonesPostNoMegusta post.id
    -else #YA NO ME GUSTA
      =cuantosMegusta "dislikes_#{post.id}", post.dislikes.count
      =botonesPostYaNoMegusta post.id

  %div
    =link_to "compartir", repost_post_path(post.id), method: :post,remote: true 


  %div{:id => "comentarios_#{post.id}"} 
    = render post.comments

  /CREAR COMENTARIOS !!!!!!!!!!!!!!!!!!!!!!!!
  =form_for [post, post.comments.build], remote: true do |f| 
   
    .mdl-textfield.mdl-js-textfield.full-width.quitarMargenAbajoComentario
      = f.text_field :body,class:"mdl-textfield__input",type:"text"  ,id: "sample1"
      = f.label :body, "Comment...",class:"mdl-textfield__label",for: "sample1"
      .ocultar.actions.text-right
        = f.submit 'Enviar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--accent"



  %div.ocultar  
    =form_for [post, post.dislikes.build], remote: true do |f|
      = f.submit 'favorite', id:"onclick-NOmegusta_#{post.id}" #BOTON  NOOO!!ME GUSTA OCULTO 
  %div.ocultar  
    =form_for [post, post.likes.build], remote: true do |f|
      = f.submit 'favorite', id:"onclick-megusta_#{post.id}" #BOTON ME GUSTA OCULTO 



      



  
  

  

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Bodyyyyy:
  = @post.body
%p
  %b User:
  = @post.user.email

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path